services:
  - type: web
    name: colortheoryai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true 